#安全中心
server:
  port: 8888
spring:
  redis:
    host: 192.168.1.93
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8


auth.security:
  oauth2:
    storeType: jwt #或者jwt
    jwtSigningKey: hongyu
    clients[0]:
      clientId: merryyou
      clientSecret: merryyou
    clients[1]:
            clientId: merryyou1
            clientSecret: merryyou1



logging:
  level:
    org.springframework: debug

accessToken.validity.seconds: 7200

#资源中心
auth-server: http://127.0.0.1:8888 # sso-server地址
security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
      user-info-uri: ${auth-server}/user/me
      token-info-uri: ${auth-server}/oauth/check_token